name: Build EXE and Release

on:
  push:
    tags:
      - 'v*'
      - 'v*.*'
      - 'v*.*.*'
      - 'v*.*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Debug PyQt6 installation
        run: |
          echo "Python version:"
          python --version
          echo "PyQt6 installation:"
          pip show PyQt6
          echo "PyQt6-Qt6 installation:"
          pip show PyQt6-Qt6
          echo "PyQt6-sip installation:"
          pip show PyQt6-sip

      - name: Create targets directory
        run: mkdir targets

      - name: Build EXE
        run: |
          pyinstaller --noconfirm Qdrop2name.spec
          mv dist/Qdrop2name.exe dist/Qdrop2name-${{ github.ref_name }}.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Qdrop2name-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
