name: Build EXE and Release

on:
  push:
    tags:
      - 'v*'
      - 'v*.*'
      - 'v*.*.*'
      - 'v*.*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install UPX for compression
        run: |
          # 下载并安装UPX压缩工具
          curl -L -o upx.zip https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip
          Expand-Archive -Path upx.zip -DestinationPath upx
          echo "$PWD/upx/upx-4.2.1-win64/upx.exe" >> $env:GITHUB_PATH

      - name: Ensure targets directory exists
        run: mkdir targets

      - name: Build EXE with PyInstaller
        shell: bash
        run: |
          pyinstaller --noconfirm Qdrop2name.spec
          mv dist/Qdrop2name.exe dist/Qdrop2name-${{ github.ref_name }}.exe

      - name: Show file size
        run: |
          echo "Final EXE size:"
          ls -lh dist/Qdrop2name-${{ github.ref_name }}.exe

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Qdrop2name-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
